version: '3'
services:
  frontend:
    build:
<<<<<<< HEAD
      context: ./angular-8-client 
    ports:
      - 8081:8081
    networks:
      - net-app  
=======
      context: ./angular-8-client
    ports:
      - 8081:8081
    networks:
      - myapp_network
>>>>>>> origin/anas-prog

  backend:
    build:
      context: ./spring-boot-server
    ports:
      - 8081:8081
    networks:
<<<<<<< HEAD
      - net-app  
    depends_on:
      - db
      
=======
      - myapp_network
    depends_on:
      - db
>>>>>>> origin/anas-prog

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
<<<<<<< HEAD
      - net-app

    
  networks:
    net-app: 
=======
      - myapp_network

networks:
  myapp_network:
    driver: bridge
>>>>>>> origin/anas-prog
