version: '3'
services:
  backend:
    build:
      context: ./spring-boot-server
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/tutorials
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    # ... other configurations for the backend service

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tutorials
    volumes:
      - ./mysql-data:/var/lib/mysql
    # ... other configurations for the MySQL service

  frontend:
    build:
      context: ./angular-8-client
    ports:
      - 8081:8081
    # ... other configurations for the frontend service
